extends: airbnb-base

plugins:
  - googleappsscript

env:
  googleappsscript/googleappsscript: true

globals:
  Props: false
  Toggl: false
  Utils: false

rules:
  no-underscore-dangle: [error, { allowAfterThis: true }]
  no-console: ["error", { allow: ["info", "warn", "error"] }]
